services:
  api:
    build: .
    container_name: api
    command: [ "api" ]
    ports:
      - "8001:8000"
    depends_on:
      - redis_app

  worker:
    build: .
    container_name: celery_worker
    command: [ "worker" ]
    depends_on:
      - redis_app

  beat:
    build: .
    container_name: celery_beat
    command: [ "beat" ]
    depends_on:
      - redis_app

  flower:
    build: .
    container_name: celery_flower
    command: [ "flower" ]
    ports:
      - "5556:5555"
    depends_on:
      - redis_app

  redis_app:
    image: redis:7
    container_name: redis-app
    ports:
      - "6380:6379"
